In [14]:
import pandas as pd
import plotly_express as px

In [15]:
df = pd.read_csv("../sleepdata.csv")
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  object
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  object
 3   Occupation                 50000 non-null  object
 4   Device_Type                50000 non-null  object
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), object(4)
memory usage: 5.0+ MB

In [17]:
df.describe()

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,39.034960,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,12.414877,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,18.000000,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,28.000000,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,39.000000,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,50.000000,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,60.000000,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

In [18]:
df.columns

Index(['User_ID', 'Age', 'Gender', 'Occupation', 'Device_Type',
       'Daily_Phone_Hours', 'Social_Media_Hours', 'Work_Productivity_Score',
       'Sleep_Hours', 'Stress_Level', 'App_Usage_Count',
       'Caffeine_Intake_Cups', 'Weekend_Screen_Time_Hours'],
      dtype='object')

In [19]:
fig = px.histogram(
    df,
    x="Sleep_Hours",
    nbins=30,
    title="Distribución de Horas de Sueño"
)

fig.show()

In [20]:
fig = px.scatter(
    df,
    x="Daily_Phone_Hours",
    y="Sleep_Hours",
    color="Stress_Level",
    title="Daily Phone Hours vs Sleep Hours"
)

fig.show()

In [21]:
fig = px.scatter(
    df,
    x="Sleep_Hours",
    y="Stress_Level",
    trendline="ols",
    title="Sleep Hours vs Stress Level"
)

fig.show()

In [22]:
fig = px.box(
    df,
    x="Gender",
    y="Stress_Level",
    title="Stress Level by Gender"
)

fig.show()

In [23]:
occupation_stress = df.groupby("Occupation")["Stress_Level"].mean().reset_index()

fig = px.bar(
    occupation_stress,
    x="Occupation",
    y="Stress_Level",
    title="Average Stress Level by Occupation"
)

fig.show()